### ISSUE TITLE
White page on articles with leaflet map using contao 3.5

### ISSUE THREAD

**Issue by taleteller** [netzmacht/contao-leaflet-maps#37]
__Problem__
When using a leaflet-map as article element, you get a white screen after saving the changes in backend and frontend every time you visit the article. 

__Reproduce__
Install Contao 3.5 as well as contao-leaflet-maps 1.0.0-beta3 ref ff8cda13 from composer. Create any map-provider and any map with it. Navigate to an article and insert it there as element. 

__Errors__
When enabling error messages you will get this output: `Fatal error: Cannot make static method Contao\Controller::replaceInsertTags() non static in class Netzmacht\Contao\Leaflet\Frontend\Helper\FrontendApi in /path/composer/vendor/netzmacht/contao-leaflet-maps/src/Netzmacht/Contao/Leaflet/Frontend/Helper/FrontendApi.php on line 30`

__Solution__
Apparently the line in question misses a `static` and should be written
```
public static function replaceInsertTags($strBuffer, $blnCache = true)
```
instead. This way everything shows correctly on both, front- and backend.

**Comment by dmolineus** [comment]
Caused by https://github.com/contao/core/commit/a96d074590ea228536c13010d58fcf1a281463eb

**Comment by dmolineus** [comment]
Should be fixed by https://github.com/netzmacht/contao-leaflet-maps/commit/3c983e86bc28253a322498586fe1a3868a0ac44f which is part of the develop branch so far.

**Comment by kikmedia** [comment]
Sorry to say that, but for me an error still occurs with Contao 3.5.2 even when using development branch (f8b65632):
```PHP Fatal error:  Call to protected Contao\System::__construct() from context 'Netzmacht\Contao\Leaflet\Frontend\Helper\InsertTagReplacer' in mypath/www/payloads/kilian/35/composer/vendor/netzmacht/contao-leaflet-maps/src/Netzmacht/Contao/Leaflet/Frontend/Helper/InsertTagReplacer.php on line 32```

**Comment by dmolineus** [comment]
Omg. Contao seems to be broken there. The new provided insert tag seems not to be callable. The protected constructor of the controller is not made public there, neighter the method is static even the class doc claims it's an static class...

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/InsertTags.php

In Contao which issue does not occur because of the *special* public/private concept of PHP. It's valid to call a protected method from the outside if being the same class.

**Comment by dmolineus** [comment]
Ref: contao/core#7946

**Comment by dmolineus** [comment]
Okay, I chose yet another workaround for this issue. Hopefully solved in 8a148ffaf8a3fa9821bb6df5330a3b9624030b7f.

**Comment by kikmedia** [comment]
Works for me now (and so sorry to hear that you are getting sick and tired). Thanks a lot!

**Comment by dmolineus** [comment]
Thanks for testing and giving feedback.
